version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "lambda-prod"
s3_bucket = "pavel-lambda-prod"
s3_prefix = "lambda1"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
